name: dotnet-pack

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.201

      - name: Pack
        run: dotnet pack AWS.Logger.sln --configuration Release

      - name: Publish
        run: |
          dotnet nuget push "src/AWS.Logger.Core/bin/Release/*.nupkg" --source https://nuget.pkg.github.com/MyClinicalOutcomesLtd/index.json -k ${{ secrets.GITHUB_TOKEN }}
          dotnet nuget push "src/AWS.Logger.AspNetCore/bin/Release/*.nupkg" --source https://nuget.pkg.github.com/MyClinicalOutcomesLtd/index.json -k ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
